# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb3bac80bd87b107830291312123c62623e7afaba5da9829c364e5afa2d1f91b30cbd51709206505a3eabdabb6a49f75c5d6de51df5bffaadd39f95bade58458

test:
  secret_key_base: b90f480988e2e3a1f5a2327d7555aa755b546751c210716a17f5834b36c95f95dfbd7fb2df6050ef4b63b9b09563714e0c187cfbec719d947ed9e886201be58a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
